### ISSUE TITLE
Python version conflict

### ISSUE THREAD

**Issue by VitaliyaIoffe** [tarantool/mkrepo#40]
I tried to use mkrepo and it raised me next error:

```
Traceback (most recent call last):
  File "./mkrepo.py", line 111, in <module>
    main()
  File "./mkrepo.py", line 107, in main
    update_repo(path, args)
  File "./mkrepo.py", line 57, in update_repo
    rpmrepo.update_repo(stor, args.sign, args.temp_dir, args.force)
  File "/Users/v.ioffe/mkrepo/rpmrepo.py", line 888, in update_repo
    primary_str, primary_gz, revision, storage)
  File "/Users/v.ioffe/mkrepo/rpmrepo.py", line 758, in generate_repomd
    other = gzip.decompress(other_gz)
AttributeError: 'module' object has no attribute 'decompress'
```

I resolved it by thus diff:
```
v.ioffe@v-ioffe mkrepo % git diff
diff --git a/mkrepo.py b/mkrepo.py
index edfa745..d1ebcd2 100755
--- a/mkrepo.py
+++ b/mkrepo.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 
 import argparse
 import storage
```

It seems that python2 is not working with mkrepo.

**Comment by ylobankov** [comment]
We officially dropped Python2 support in the latest release (v1.0.0). So closing this issue. It will not be fixed.
